# Name of workflow
name: CI

# Define the trigger event(s)
on: [push] # Push request

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  # Job to build and do static analysis
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: anguyen00/msp430gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Get all submodules (linked repo's instead of copied (i.e. externals/printf))
      - name: Format source files with clang
        run: make format && git diff
      - name: Run static analysis
        run: make cppcheck
      - name: Build (compile and link) code for Launchpad
        run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=LAUNCHPAD
      - name: Build (compile and link) code for SumoBot (PCB)
        run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=SUMOBOT

