# Name of workflow
name: CI

# Define the trigger event(s)
on: [push] # Push request

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  # Job to build and do static analysis
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: anguyen00/msp430gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: TOOLS_PATH=/home/ubuntu/dev/tools/ make
      - run: make cppcheck

