# Name of workflow
name: Test Workflow

# Define the trigger event(s)
on: [push] # Push request

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  # Job to build and do static analysis
  build_and_static_analysis:
    runs-on: mint-latest
    container:
      image: alexn/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: make
      - run: make cppcheck

